### ISSUE TITLE
Device doesn't go to deep sleep if AOD is on in crDroid

### ISSUE THREAD

**Issue by Rajdeep97** [GZR-Kernels/Optimus_Drunk_Alioth#1]
New Bug:
Using Optimus Kernel v11.2 with cRDroid 7.7

In cRDroid, if AOD is enabled the device doesn't go to deep sleep, even with dt2w & pocket detection disabled, however if does so in Arrow.

It goes to deep sleep only if AOD is off.

Can you please check?

**Comment by GtrCraft** [comment]
I picked the commit already, next release will have it.
