### ISSUE TITLE
[Question] Proximity sensor

### ISSUE THREAD

**Issue by 1alessandro1** [GZR-Kernels/Optimus_Drunk_Alioth#2]
Hi, thank you for this kernel, it's been working very well ok crDroid 7.9/7.10 on alioth.

However I cannot understand why the proximity sensor was disabled only on telegram with the latest update (and the latest alioth firmware from xiaomifirmwareupdater) and all other messaging apps like WhatsApp, are working fine with that proximity sensor.

Could you provide more info on this decision?

Thank you, hope to hear from you soon

**Comment by GtrCraft** [comment]
Because proximity sensor is enabled every time audio is playing in telegram.
Which is a waste of battery.
