### ISSUE TITLE
many issue with double tap to wake featur 

### ISSUE THREAD

**Issue by ale82to** [GZR-Kernels/Optimus_Drunk_Alioth#4]
since I ve got these "problems" on two different rooms  (Droid on time and official lineage OS 18.1) it might worth reporting.
double tap to wake feature is NOT disabled in pocket(to reproduce the issue both aod and ambient display must be turned off) as it should (tested on my old mi 10 Lite for reference , covering, proximity /light sensor and performing double tap to wake screen is still weaken up ).
also, different issue, double tap to wake is very very unreliable it almost always requires 3/4 tap to actually weak up the phone.
keep in mind that the problems only happen if aod is disabled :if aod with show notification is on double tap to wake is both always reliable in waking up the phone and in NOT turning it on in the pocket because it relies on sensors.
at this point I know I can just use aod (with additional setting of showing notification turned on) but battery drain is totally insane about 8%/hour so is not an option for me.
if I can provide further details please let me know and thanks for this amazing kernel.

**Comment by GtrCraft** [comment]
Those are not kernel issues
