### ISSUE TITLE
Sky: Children of the Light

### ISSUE THREAD

**Issue by akippnn** [GZR-Kernels/Optimus_Drunk_Alioth#5]
The game is broken on Sky: Children of Light

I am using Pixel Extended ROM.

[Same issue as this reply but with a different ROM ](https://forum.xda-developers.com/t/kernel-alioth-optimus-drunk-kernel-v11-28-08-12.4302055/post-85978349)

Can please fix this issue?

**Comment by GtrCraft** [comment]
Just tested myself and the game starts and plays fine.
Maybe try AICP and see if the game works. Because I fixed the scaling on that rom.
