### ISSUE TITLE
wrong screen size

### ISSUE THREAD

**Issue by alex9yust** [GZR-Kernels/Optimus_Drunk_Alioth#6]
https://github.com/GZR-Kernels/Optimus_Drunk_Alioth/blob/a1d5432af9e62421423a425231fe079322ef39eb/arch/arm64/boot/dts/vendor/qcom/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi#L26

it should be something like this

		qcom,mdss-pan-physical-width-dimension = <70>;
		qcom,mdss-pan-physical-height-dimension = <154>;

check - try to open the table in Google Tables

**Comment by GtrCraft** [comment]
Where did you get those values?

**Comment by alex9yust** [comment]
divided by 10. removed two zeros. 
By the way, gesture in youtube works.

and you already had it.
https://github.com/GZR-Kernels/Optimus_Drunk_Alioth/commit/09da2cdabc9dd7b5812c13add58c32a79280c83b#diff-4f1a632b48b777fe480968c6e9803111564601f4e8a89c3d7b7270f1584945a1
